### ISSUE TITLE
FinalBurn Neo Support

### ISSUE THREAD

**Issue by Firdoser** [tiduscrying/MiniUI-Extra-Extras#15]
Could you include the RetroArch FinalBurn Neo core to play arcade games? The core is much more stable and supports multiple systems. (NeoGeo,Cave,Cps1 etc)

**Comment by tiduscrying** [comment]
Final Burn Alpha already has support for NeoGeo, CPS1, CPS2 and CPS3 plus other various boards. I do recommend using the standalone CPS2 and CPS3 cores since they have slightly better performance, but aside from that the core is pretty stable from my testing.  Is there something that doesn't play well with that core that Neo would do better with?

**Comment by hotbarlo** [comment]
Adding my two cents here. Street Fighter III ur1 romset starts ok with current CPS-3 core, but gets super slow after a while.

On Onion, FBNEO runs it at full speed to the end. I tried creating a Pak for it using the same Onion core, but I could not get it to run. What I mean is, I'd appreciate if you manage to do it, @tiduscrying! And thanks for the other cores as well!

**Comment by Firdoser** [comment]
> 

For example Neo Geo games run with too much lag, or Cps2 games without frameskip don't run well, Personally, the FinalBurn Neo core has extra options like blitter, throttle, cpu overclock, etc. Options that are essential for Shoot em up games

**Comment by tiduscrying** [comment]
I can't seem to get FBNeo to run on my end, unfortunately. Tried both with and without swap, but it segfaults regardless. Someone a bit smarter than me might need to take a crack at it to get it working. My apologies!

**Comment by hotbarlo** [comment]
Thank you for trying, @tiduscrying !
