### ISSUE TITLE
Chex Quest Loses Walls/Trailing

### ISSUE THREAD

**Issue by thisisredlitre** [tiduscrying/MiniUI-Extra-Extras#5]
Hi there,

Thank you for putting this together I really enjoy it. Just wanted to bring up when I load in Chex Quest on my Miyoo the walls don't load/everything trails in the background where the walls should be. So far my cursory google-fu is failing me so I thought i might ask you here.

Thank you in advance!

**Comment by tiduscrying** [comment]
Hi there, I believe what might be happening is that Chex Quest is trying to load in with the Doom2.wad instead of Doom.wad. Inside the folder for it, make sure that you have either Doom.wad or Freedoom.wad! 

Additionally, if that doesn't work, be sure to enable the feature in Picoarch's advanced menu that _disables_ looking for the parent IWAD in additional folders, since that apparently is required to run some mods.

**Comment by thisisredlitre** [comment]
That got it! thank you!
